### ISSUE TITLE
Factory reset time

### ISSUE THREAD

**Issue by Gathiyo** [frankaemika/libfranka#33]
How much time does it take for the robot to execute the factory reset? We are on the version 2.1.1.

**Comment by fwalch** [comment]
A factory reset reboots the system, but otherwise doesn't take much time. After the reboot has finished, you should see the first-start dialog when you connect.

In general, questions/problems not directly related to libfranka should rather be posted to the [community](https://www.franka-community.de/) or sent to our [support email](http://support.franka.de/) :)
