### ISSUE TITLE
Include headers missing

### ISSUE THREAD

**Issue by nash169** [frankaemika/libfranka#65]
Hi,
I've noticed that a couple of include headers are missing and this might break the compilation some time.

In include/franka/control_tools.h missing string
In include/franka/control_types.h missing stdexcept

**Comment by otherwiseopen** [comment]
Hi,
do you plan to update the 0.8.* release and the [libfranka-release repo](https://github.com/frankaemika/libfranka-release) with this fix? Currently, it is not possible building a Franka-enabled ROS from source using the [recommended process](http://wiki.ros.org/noetic/Installation/Source) without some awkward workarounds (at least on Fedora 33/34), which is unfortunate, since the problem has been fixed for quite a while.

**Comment by AndreasKuhner** [comment]
Hi @nash169 ,
I think the issue is resolved by now... if not, please open again. Thank you!

Cheers,
Andreas
